# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

apply_ptsl_helper <- function(value, date, start, end, side, lower, upper) {
    .Call(`_finma_apply_ptsl_helper`, value, date, start, end, side, lower, upper)
}

